experiment_name: "Asperity_Inverse_Design_v1"

physics:
  n_asperities: 16
  max_delta_ratio: 0.1
  radius: 1.0
  E_star: 1.0

data:
  path: "data/dataset_16_asp.pt"
  n_steps: 50
  n_samples: 10000

model:
  hidden_dim: 256

training:
  batch_size: 64
  epochs: 100
  learning_rate: 0.001
  device: "cpu" #"cuda"